import type { ImageSource } from "expo-image";

/**
 * Maps emoji strings used in data definitions → bundled pixel-art PNGs.
 * `require()` is necessary here because Metro needs static string literals
 * for asset resolution at build time.
 */
export const ICON_MAP: Record<string, ImageSource> = {
  // Weather
  "🔥": require("@/assets/icons/fire.png"),
  "☀️": require("@/assets/icons/sunny.png"),
  "🌤️": require("@/assets/icons/partly-cloudy.png"),
  "☁️": require("@/assets/icons/cloudy.png"),
  "🌧️": require("@/assets/icons/rainy.png"),
  "⛈️": require("@/assets/icons/stormy.png"),
  "🌦️": require("@/assets/icons/mixed-weather.png"),
  "🌡️": require("@/assets/icons/thermometer.png"),
  "❄️": require("@/assets/icons/snowflake.png"),
  "🥶": require("@/assets/icons/freezing.png"),

  // Ingredients
  "🍋": require("@/assets/icons/lemon.png"),
  "🍬": require("@/assets/icons/sugar.png"),
  "🧊": require("@/assets/icons/ice.png"),
  "🥤": require("@/assets/icons/cup.png"),
  "🍯": require("@/assets/icons/honey.png"),
  "🫗": require("@/assets/icons/pouring.png"),

  // Events
  "🎪": require("@/assets/icons/carnival.png"),
  "🚧": require("@/assets/icons/construction-event.png"),
  "🔬": require("@/assets/icons/science.png"),
  "📈": require("@/assets/icons/trending-up.png"),
  "📰": require("@/assets/icons/news.png"),
  "⚡": require("@/assets/icons/lightning.png"),
  "🎒": require("@/assets/icons/backpack.png"),
  "🏪": require("@/assets/icons/shop.png"),
  "🏷️": require("@/assets/icons/price-tag.png"),

  // Upgrades — Stand / Signage / Cooling / Storage
  "🔨": require("@/assets/icons/hammer.png"),
  "🗂️": require("@/assets/icons/card-dividers.png"),
  "🏢": require("@/assets/icons/office.png"),
  "🪧": require("@/assets/icons/sign.png"),
  "📦": require("@/assets/icons/package.png"),
  "🗃️": require("@/assets/icons/file-box.png"),
  "📓": require("@/assets/icons/notebook.png"),
  "🧥": require("@/assets/icons/coat.png"),
  "📄": require("@/assets/icons/paper.png"),
  "🧻": require("@/assets/icons/roll.png"),
  "📋": require("@/assets/icons/clipboard.png"),
  "🔪": require("@/assets/icons/knife.png"),
  "🫙": require("@/assets/icons/jar.png"),
  "📻": require("@/assets/icons/radio.png"),
  "🧮": require("@/assets/icons/abacus.png"),
  "🎨": require("@/assets/icons/art.png"),
  "🛒": require("@/assets/icons/cart.png"),
  "🖊️": require("@/assets/icons/pen.png"),
  "🗄️": require("@/assets/icons/cabinet.png"),
  "☂️": require("@/assets/icons/umbrella.png"),
  "💼": require("@/assets/icons/briefcase.png"),
  "🍽️": require("@/assets/icons/dining.png"),
  "📝": require("@/assets/icons/memo.png"),
  "📊": require("@/assets/icons/bar-chart.png"),
  "🌸": require("@/assets/icons/blossom.png"),
  "🎀": require("@/assets/icons/ribbon.png"),
  "⛺": require("@/assets/icons/tent.png"),
  "🪵": require("@/assets/icons/log.png"),
  "🏕️": require("@/assets/icons/camping.png"),
  "🪑": require("@/assets/icons/chair.png"),
  "🌾": require("@/assets/icons/wheat.png"),
  "🏺": require("@/assets/icons/vase.png"),
  "👤": require("@/assets/icons/person.png"),
  "📱": require("@/assets/icons/phone.png"),
  "💡": require("@/assets/icons/lightbulb.png"),
  "🌳": require("@/assets/icons/tree.png"),
  "💳": require("@/assets/icons/credit-card.png"),
  "🏭": require("@/assets/icons/factory.png"),
  "🏠": require("@/assets/icons/house.png"),
  "💎": require("@/assets/icons/diamond.png"),
  "🔊": require("@/assets/icons/speaker.png"),
  "👷": require("@/assets/icons/worker.png"),
  "💻": require("@/assets/icons/laptop.png"),
  "🎭": require("@/assets/icons/theater.png"),
  "🛡️": require("@/assets/icons/shield.png"),
  "🎉": require("@/assets/icons/party.png"),
  "🤫": require("@/assets/icons/secret.png"),
  "🏬": require("@/assets/icons/dept-store.png"),
  "📺": require("@/assets/icons/tv.png"),
  "🤳": require("@/assets/icons/selfie.png"),
  "🎖️": require("@/assets/icons/medal.png"),
  "🚚": require("@/assets/icons/truck.png"),
  "🤖": require("@/assets/icons/robot.png"),
  "👔": require("@/assets/icons/tie.png"),
  "🏆": require("@/assets/icons/trophy.png"),
  "📲": require("@/assets/icons/mobile.png"),
  "📜": require("@/assets/icons/scroll.png"),
  "🚐": require("@/assets/icons/van.png"),
  "🖥️": require("@/assets/icons/desktop.png"),
  "🏔️": require("@/assets/icons/mountain.png"),
  "👨‍🍳": require("@/assets/icons/chef.png"),
  "🌍": require("@/assets/icons/globe.png"),
  "🚗": require("@/assets/icons/car.png"),
  "👥": require("@/assets/icons/people.png"),
  "🛵": require("@/assets/icons/scooter.png"),
  "🌟": require("@/assets/icons/star.png"),
  "⭐": require("@/assets/icons/star.png"),
  "🏟️": require("@/assets/icons/stadium.png"),
  "🏰": require("@/assets/icons/castle.png"),
  "⚗️": require("@/assets/icons/alchemy.png"),
  "🧖": require("@/assets/icons/spa.png"),
  "📡": require("@/assets/icons/satellite.png"),
  "💨": require("@/assets/icons/wind.png"),
  "⚔️": require("@/assets/icons/swords.png"),

  // Achievements
  "💯": require("@/assets/icons/hundred.png"),
  "🏦": require("@/assets/icons/bank.png"),
  "💪": require("@/assets/icons/strong.png"),
  "👑": require("@/assets/icons/crown.png"),
  "🪙": require("@/assets/icons/coin.png"),
  "📅": require("@/assets/icons/calendar.png"),

  // UI / Misc
  "💸": require("@/assets/icons/money-flying.png"),
  "🏅": require("@/assets/icons/sports-medal.png"),
};
